# Generated by Django 6.0.5 on 2026-05-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('account_identifier', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='other', max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'account_identifier'), name='uniq_account_institution_identifier')],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=500)),
                ('source_institution', models.CharField(max_length=100)),
                ('source_profile', models.CharField(blank=True, default='', max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('row_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='money_observability.account')),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_json', models.JSONField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_transactions', to='money_observability.importbatch')),
            ],
            options={
                'ordering': ['import_batch', 'row_number'],
                'unique_together': {('import_batch', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_key', models.CharField(max_length=64, unique=True)),
                ('event_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_native_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('source_file', models.CharField(max_length=500)),
                ('source_institution', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description_raw', models.TextField()),
                ('description_clean', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('original_currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money_observability.account')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money_observability.importbatch')),
                ('raw_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='money_observability.rawtransaction')),
            ],
            options={
                'ordering': ['-posted_date', 'description_raw'],
            },
        ),
    ]
