# Generated by Django 6.0.5 on 2026-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_profile',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
