# Generated by Django 6.0.5 on 2026-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='excluded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exclusion_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exclusion_rule_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
