# Generated by Django 6.0.5 on 2026-05-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_observability', '0004_budget_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='raw_transaction',
        ),
        migrations.DeleteModel(
            name='RawTransaction',
        ),
    ]
