# Generated by Django 6.0.5 on 2026-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("money_observability", "0005_remove_transaction_raw_transaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="budget_treatment",
        ),
    ]
